import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import ToastProvider from "./ToastProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.svg" sizes="32x32" />
				<ColorSchemeScript />
			</head>

			<body className={inter.className}>
				<main>
					<MantineProvider
						theme={{
							primaryColor: "dark",
						}}
					>
						<ToastProvider>{children}</ToastProvider>
					</MantineProvider>
				</main>
			</body>
		</html>
	);
}
